ASP.NET MVC/Twitter/Twitter.Web/Models/ViewModels/CreateTweetViewModel.cs
namespace Twitter.Web.Models.ViewModels
{
    using System.ComponentModel.DataAnnotations;

    public class CreateTweetViewModel
    {
        [Required]
        [MinLength(1)]
        [MaxLength(1000)]
        public string Content { get; set; }
    }
}

ASP.NET MVC/Twitter/Twitter.Web/Controllers/TweetsController.cs
namespace Twitter.Web.Controllers
{
    using Microsoft.AspNet.Identity;
    using System;
    using System.Web.Mvc;
    using Twitter.Models;
    using Models.ViewModels;
    using Models.BindingModels;

    [Authorize]
    public class TweetsController : BaseController
    {
        [OutputCache(Duration = 5 * 60)]
        public ActionResult CreateTweet()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateTweet(CreateTweetBindingModel model)
        {
            if (this.ModelState.IsValid && this.ModelState != null)
            {
                var loggedUserId = User.Identity.GetUserId();

                var tweet = new Tweet
                {
                    Content = model.Content,
                    CreatedAt = DateTime.Now,
                    AuthorId = loggedUserId
                };

                this.Data.Tweets.Add(tweet);
                this.Data.SaveChanges();
                this.TempData["SuccessMessage"] = "Tweet successfully created!";

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }
    }
}

ASP.NET MVC/Twitter/Twitter.Web/Views/Tweets/CreateTweet.cshtml
@model Twitter.Web.Models.BindingModels.CreateTweetBindingModel

@{
    ViewBag.Title = "Create tweet";
}

<h2>Create new tweet</h2>

@using (Html.BeginForm("CreateTweet", "Tweets", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="col-md-1">
            @Html.LabelFor(m => m.Content)
        </div>
        <div class="col-md-11">
            <p class="text-danger">@Html.ValidationMessageFor(m => m.Content)</p>
            @Html.EditorFor(m => m.Content)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-1 col-md-11">
            <input type="submit" class="btn btn-default" value="Tweet" />
        </div>
    </div>
}

@section scripts {
    @Scripts.Render("~/bundles/jqueryval");
}