ASP.NET MVC/Exam/preparation/Sport system author solution/SportSystem.App/Controllers/MatchesController.cs
namespace SportSystem.App.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using AutoMapper;
    using Data.UnitOfWork;
    using Models.ViewModels;
    using System.Data.Entity;
    using System.Linq;

    public class MatchesController : BaseController
    {
        public MatchesController(ISportSystemData data)
            : base(data)
        {
        }

        public ActionResult Index(int page = 1, int count = 5)
        {
            var matches = this.Data.Matches.All();
            int matchesCount = matches.Count();
            matches = matches
                .Include(m => m.HomeTeam)
                .Include(m => m.AwayTeam)
                .OrderBy(m => m.DateAndTime)
                .Skip((page - 1) * count)
                .Take(count);
            this.ViewBag.TotalPages = (matchesCount + count - 1) / count;
            this.ViewBag.CurrentPage = page;
            var model = Mapper.Map<IEnumerable<ConciseMatchViewModel>>(matches);
            return this.View(model);
        }
    }
}

ASP.NET MVC/Exam/preparation/Sport system author solution/SportSystem.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sport System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("All Matches", "Index", "Matches")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.Partial("_Messages")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sport System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ASP.NET MVC/Exam/preparation/Sport system author solution/SportSystem.App/Views/Shared/_Messages.cshtml
@if (TempData.ContainsKey("message"))
{
    <div class="alert alert-success">@TempData["message"]</div>
}